name: "Setup Godot CI/CD"
description: "Setup Godot (with or without .NET) on macOS, Linux CI/CD runners."
author: "Niranjan Shk"
branding:
  icon: "play"
  color: "blue"

inputs:
  version:
    description: "Godot version (e.g. 4.2.1)"
    required: true
  headless:
    description: "Install headless version (Linux only). Ignored on macOS."
    required: false
    default: "true"
  dotnet:
    description: "Install the .NET / mono version (adds C# support). Also selects the matching mono export-template archive when install-export-templates is true."
    required: false
    default: "false"
  install-export-templates:
    description: "Download and install export templates into the standard Godot templates directory."
    required: false
    default: "false"

outputs:
  godot-path:
    description: Absolute path to the installed godot binary.
    value: ${{ steps.set-var.outputs.godot-path }}
  templates-path:
    description: Absolute path to the export-templates directory (empty string when install-export-templates is false).
    value: ${{ steps.set-var.outputs.templates-path }}

runs:
  using: "composite"
  steps:
    - name: Set variables
      id: set-var
      shell: bash
      env:
        INPUT_VERSION:   ${{ inputs.version }}
        INPUT_HEADLESS:  ${{ inputs.headless }}
        INPUT_DOTNET:    ${{ inputs.dotnet }}
        INPUT_TEMPLATES: ${{ inputs.install-export-templates }}
        RUNNER_OS:       ${{ runner.os }}
      run: |
        set -euo pipefail

        VERSION="${INPUT_VERSION}"
        TAG="${VERSION}-stable"
        GH_BASE="https://github.com/godotengine/godot/releases/download/${TAG}"

        MONO_PREFIX=""
        if [[ "${INPUT_DOTNET}" == "true" ]]; then
          MONO_PREFIX="mono_"
        fi

        # Export-template asset name is the same on every platform.
        TPL_ASSET="Godot_v${VERSION}-stable_${MONO_PREFIX}export_templates.tpz"

        # Per-platform variables 
        if [[ "${RUNNER_OS}" == "Linux" ]]; then
          HEADLESS_SUFFIX=""
          if [[ "${INPUT_HEADLESS}" == "true" ]]; then
            HEADLESS_SUFFIX=".headless"
          fi
          ASSET_NAME="Godot_v${VERSION}-stable_${MONO_PREFIX}linux.x86_64${HEADLESS_SUFFIX}.zip"
          GODOT_BIN_DIR="${HOME}/.local/bin"
          GODOT_INSTALL_DIR="${HOME}/.local/share/godot/install"
          GODOT_PATH="${GODOT_BIN_DIR}/godot"
          TEMPLATES_DIR="${HOME}/.local/share/godot/templates/${VERSION}.stable"

        elif [[ "${RUNNER_OS}" == "macOS" ]]; then
          ASSET_NAME="Godot_v${VERSION}-stable_${MONO_PREFIX}macos.universal.zip"
          GODOT_BIN_DIR="${HOME}/.local/bin"
          GODOT_INSTALL_DIR="${HOME}/.local/share/godot/install"
          GODOT_PATH="${GODOT_BIN_DIR}/godot"
          TEMPLATES_DIR="${HOME}/Library/Application Support/godot/templates/${VERSION}.stable"

        else
          echo "ERROR: unsupported runner OS: ${RUNNER_OS}" >&2
          exit 1
        fi

        # Add binary directory to PATH for future steps
        echo "${GODOT_BIN_DIR}" >> "$GITHUB_PATH"

        # Persist for all later steps 
        {
          echo "VERSION=${VERSION}"
          echo "TAG=${TAG}"
          echo "GH_BASE=${GH_BASE}"
          echo "ASSET_NAME=${ASSET_NAME}"
          echo "TPL_ASSET=${TPL_ASSET}"
          echo "GODOT_BIN_DIR=${GODOT_BIN_DIR}"
          echo "GODOT_INSTALL_DIR=${GODOT_INSTALL_DIR}"
          echo "GODOT_PATH=${GODOT_PATH}"
          echo "TEMPLATES_DIR=${TEMPLATES_DIR}"
        } >> "$GITHUB_ENV"

        # Step outputs for downstream jobs 
        TPL_OUT=""
        if [[ "${INPUT_TEMPLATES}" == "true" ]]; then
          TPL_OUT="${TEMPLATES_DIR}"
        fi
        {
          echo "godot-path=${GODOT_PATH}"
          echo "templates-path=${TPL_OUT}"
        } >> "$GITHUB_OUTPUT"

        echo "=== Resolved asset : ${ASSET_NAME}"
        echo "=== Download URL   : ${GH_BASE}/${ASSET_NAME}"

    - uses: actions/cache@v4
      id: cache-editor
      with:
        path: /tmp/godot-cache/editor
        key: godot-editor-${{ runner.os }}-${{ inputs.version }}-dotnet-${{ inputs.dotnet }}-headless-${{ inputs.headless }}

    - uses: actions/cache@v4
      id: cache-templates
      if: inputs.install-export-templates == 'true'
      with:
        path: /tmp/godot-cache/templates
        key: godot-templates-${{ runner.os }}-${{ inputs.version }}-dotnet-${{ inputs.dotnet }}

    - name: Download Godot editor
      shell: bash
      if: steps.cache-editor.outputs.cache-hit != 'true'
      run: |
        set -euo pipefail
        mkdir -p /tmp/godot-cache/editor
        echo "Downloading ${GH_BASE}/${ASSET_NAME} …"
        curl -sL -o "/tmp/godot-cache/editor/${ASSET_NAME}" "${GH_BASE}/${ASSET_NAME}"
        echo "Download complete: $(du -h "/tmp/godot-cache/editor/${ASSET_NAME}" | cut -f1)"

    - name: Install Godot (Linux)
      shell: bash
      if: runner.os == 'Linux'
      run: |
        set -euo pipefail
        mkdir -p /tmp/godot-install
        unzip -o "/tmp/godot-cache/editor/${ASSET_NAME}" -d /tmp/godot-install

        # Move contents to install dir
        mkdir -p "${GODOT_INSTALL_DIR}"
        # We use dotglob if set, but simple * usually works only for non-hidden.
        # To be safe, just move valid items.
        mv -f /tmp/godot-install/* "${GODOT_INSTALL_DIR}/"

        # Find binary (depth 2 allows for nested folder in zip)
        BINARY=$(find "${GODOT_INSTALL_DIR}" -maxdepth 2 -type f -executable | head -1)
        if [[ -z "${BINARY}" ]]; then
          echo "ERROR: no executable found in ${GODOT_INSTALL_DIR}" >&2
          find "${GODOT_INSTALL_DIR}"
          exit 1
        fi

        mkdir -p "${GODOT_BIN_DIR}"
        ln -sf "${BINARY}" "${GODOT_PATH}"
        chmod +x "${BINARY}"
        
        echo "Installed: ${GODOT_PATH} -> ${BINARY}"

    - name: Install Godot (macOS)
      shell: bash
      if: runner.os == 'macOS'
      run: |
        set -euo pipefail
        mkdir -p /tmp/godot-install
        unzip -o "/tmp/godot-cache/editor/${ASSET_NAME}" -d /tmp/godot-install

        # Move app bundle to install dir
        mkdir -p "${GODOT_INSTALL_DIR}"
        if [[ -d "/tmp/godot-install/Godot.app" ]]; then
            mv -f "/tmp/godot-install/Godot.app" "${GODOT_INSTALL_DIR}/"
        else
            echo "ERROR: Godot.app not found in extracted files"
            ls -R /tmp/godot-install
            exit 1
        fi

        APP_BIN="${GODOT_INSTALL_DIR}/Godot.app/Contents/MacOS/Godot"
        if [[ ! -f "${APP_BIN}" ]]; then
           echo "ERROR: Binary not found at ${APP_BIN}"
           exit 1
        fi

        mkdir -p "${GODOT_BIN_DIR}"
        ln -sf "${APP_BIN}" "${GODOT_PATH}"
        chmod +x "${APP_BIN}"

        xattr -d com.apple.quarantine "${GODOT_INSTALL_DIR}/Godot.app" 2>/dev/null || true
        echo "Installed: ${GODOT_PATH} -> ${APP_BIN}"

    - name: Download export templates
      shell: bash
      if: >-
        inputs.install-export-templates == 'true' &&
        steps.cache-templates.outputs.cache-hit != 'true'
      run: |
        set -euo pipefail
        mkdir -p /tmp/godot-cache/templates
        echo "Downloading ${GH_BASE}/${TPL_ASSET} …"
        curl -sL -o "/tmp/godot-cache/templates/${TPL_ASSET}" "${GH_BASE}/${TPL_ASSET}"
        echo "Download complete: $(du -h "/tmp/godot-cache/templates/${TPL_ASSET}" | cut -f1)"

    - name: Install export templates
      shell: bash
      if: inputs.install-export-templates == 'true'
      run: |
        set -euo pipefail
        mkdir -p "${TEMPLATES_DIR}"

        unzip -o "/tmp/godot-cache/templates/${TPL_ASSET}" -d /tmp/godot-templates-extract

        if [[ -d /tmp/godot-templates-extract/templates ]]; then
          cp -r /tmp/godot-templates-extract/templates/* "${TEMPLATES_DIR}/"
        else
          cp -r /tmp/godot-templates-extract/* "${TEMPLATES_DIR}/"
        fi

        echo "Export templates installed to: ${TEMPLATES_DIR}"
        echo "Contents:"
        ls -la "${TEMPLATES_DIR}"

    - name: Verify Godot installation
      shell: bash
      env:
        INPUT_TEMPLATES: ${{ inputs.install-export-templates }}
      run: |
        set -euo pipefail
        echo "=== Godot binary ==="
        ls -la "${GODOT_PATH}"

        echo ""
        echo "=== Version check ==="
        "${GODOT_PATH}" --headless --version

        if [[ "${INPUT_TEMPLATES}" == "true" ]]; then
          echo ""
          echo "=== Export templates ==="
          ls "${TEMPLATES_DIR}"
        fi
